### ISSUE TITLE
can't install on Windows 10

### ISSUE THREAD

**Issue by hmz22** [hthetiot/node-snowball#13]
Hi when install in react give this error log.
please tell me how fix it:
[2019-10-24T08_55_05_361Z-debug.log](https://github.com/hthetiot/node-snowball/files/3766655/2019-10-24T08_55_05_361Z-debug.log)

**Comment by hmz22** [comment]
node v10.10.0
os: windows 10 1903

**Comment by rm-hull** [comment]
Looking at the log you provided, it seems like node-gyp is failing on Windows 10. I don’t have a Windows machine to test on unfortunately, but you could try the steps outlined here: https://gist.github.com/jtrefry/fd0ea70a89e2c3b7779c. If that works, please report back and I will update the readme accordingly.

**Comment by rm-hull** [comment]
closing - no response
