### ISSUE TITLE
Russian missing in README list

### ISSUE THREAD

**Issue by niftylettuce** [hthetiot/node-snowball#15]
In the list here <https://github.com/hthetiot/node-snowball#supported-language-second-argument> "russian" is missing.

**Comment by rm-hull** [comment]
Can you clarify what you mean:
- Russian is fully supported, and it is just missing off the list
- You require Russian language to be supported and would like it to be added to the library

**Comment by niftylettuce** [comment]
"Russian is fully supported, and it is just missing off the list" - I believe this is the case, I am not 100% certain, but it seems like the only one not listed.

**Comment by rm-hull** [comment]
Yes, you are correct, it looks like Russian is supported:

https://github.com/hthetiot/node-snowball/blob/master/src/libstemmer/libstemmer/modules.h#L36-L37
