### ISSUE TITLE
README lacks documentation regarding error handling

### ISSUE THREAD

**Issue by niftylettuce** [hthetiot/node-snowball#17]
If an error occurs or if the stemmer was not created, then an error is thrown.  This documentation is completely missing from the README.

```sh
Error: Could not create stemmer.
    at Object.stemword (<anonymous>)
    at /Users/test/Projects/spamscanner/index.js:927:29
    at Array.map (<anonymous>)
    at SpamScanner.getTokens (/Users/test/Projects/spamscanner/index.js:916:47)
    at /Users/test/Projects/spamscanner/index.js:967:42
    at Array.map (<anonymous>)
    at SpamScanner.getTokensAndMailFromSource (/Users/test/Projects/spamscanner/index.js:955:21)
    at runMicrotasks (<anonymous>)
```

**Comment by rm-hull** [comment]
I think there is a reasonable expectation that if an error occurs or if the stemmer was not created then an error is thrown - I would assume most developers would expect this is the default behaviour without recourse to documentation, but please feel free to add a PR.

I would be more interested in a reproducible code snippet how you got that error - for example, did you supply a language that is unsupported? If so, then it probably is reasonable to add a line in the documentation along the lines of _"Any other language value will result in an error being thrown."_ in https://github.com/hthetiot/node-snowball#supported-language-second-argument

**Comment by niftylettuce** [comment]
No I used a supported language but with some random gibberish string.

**Comment by hthetiot** [comment]
> No I used a supported language but with some random gibberish string.

`I would be more interested in a reproducible code snippet how you got that error`
Provide full example.

**Comment by niftylettuce** [comment]
```sh
❯ node
Welcome to Node.js v12.18.0.
Type ".help" for more information.
> const snowball = require('node-snowball');
undefined
> snowball.stemword('h', 'chinese');
Uncaught Error: Could not create stemmer.
> snowball.stemword('h', 'english');
'h'
> snowball.stemword('h', 'japanese');
Uncaught Error: Could not create stemmer.
>
```

**Comment by niftylettuce** [comment]
oh wait, these aren't supported, hmm
