### ISSUE TITLE
Some word have wrong result

### ISSUE THREAD

**Issue by baguse** [hthetiot/node-snowball#22]
im tried to stemming word "trying" it gave result "tri", "does" gave result "doe"

**Comment by rm-hull** [comment]
What result are you expecting for "trying" and "does" ?

**Comment by baguse** [comment]
trying => try
does => do

isnt it?
i also test trying, tried, and try returned result "tri"

**Comment by rm-hull** [comment]
Try the 'official' demo site here: https://snowballstem.org/demo.html 

Snowball stemming will always turn "trying", "tried", and "try" all into "tri".

Look at the algorithm: https://snowballstem.org/algorithms/porter/stemmer.html
