### ISSUE TITLE
Add @rm-hull as collaborator on npmjs.org

### ISSUE THREAD

**Issue by hthetiot** [hthetiot/node-snowball#5]
@rm-hull can you create an npm account or give me your username for me to allow you to publish or appear on the npm page.

<img width="1242" alt="screen shot 2016-12-01 at 3 56 37 pm" src="https://cloud.githubusercontent.com/assets/8635/20817846/d80978ea-b7de-11e6-893e-6eb2955737eb.png">

**Comment by rm-hull** [comment]
@hthetiot - try _rm-hull_ again - just added

**Comment by hthetiot** [comment]
Done :)
https://www.npmjs.com/package/node-snowball
