### ISSUE TITLE
Crash if the language is not supported

### ISSUE THREAD

**Issue by cedrou** [hthetiot/node-snowball#6]
The module crashes the app if the provided language is not supported.

    snowball.stemword("Hello world !", "tl");

In the native module, the method `sb_stemmer_new` returns NULL if the language is not supported, but the pointer is not checked after...

**Comment by rm-hull** [comment]
@cedrou can you paste the console output or stack trace when this happens?

**Comment by cedrou** [comment]
There is no console output... The app is crashing silently...

**Comment by cedrou** [comment]
I managed to make it work by returning the input string or array if the stemmer is NULL.

**Comment by rm-hull** [comment]
Ok, I'll have a look at making it throw an exception and add a test
