### ISSUE TITLE
Add new stemmer written by snowball to node-snowball 

### ISSUE THREAD

**Issue by LBenzahia** [hthetiot/node-snowball#7]
Hello @hthetiot , 
I'm working on new arabic semmer , This stemmer has been added to snowball this year, and i want to add arabic-stemmer to node-snowball .
please can you help me !
Which steps should i follow to add new stemmer to node-snowball?
Best regard !

**Comment by rm-hull** [comment]
Hello, I think this lib took a copy of the old (now frozen) libstemmer sources and built from that. 

Looking at https://github.com/snowballstem/snowball/commit/49c147e6630049af045c84e50fdadfe56f09ad9e I can see an Arabic stemmer. Presumably this is the one you have been working on?

I took a look at the readme and saw that there might be a new .tgz, but the link at https://github.com/snowballstem/snowball/blob/master/doc/libstemmer_c_README#L7 gives a 404

If we can get hold of the latest files, I'd happily commit them and we can build a release from that.

**Comment by LBenzahia** [comment]
Hello , thanks a lot for your response Rm-hull.
Arabic stemmer added by Assem Chili in the last year, Actually i'm workin on it( improvement, binding  it with other languages, and adding it within libraries like node_snowball ).
you can check out our repo  on github [arabic-stemmer](https://github.com/assem-ch/arabicstemmer) for getting the latest  libstemmer_c  after building the code at your machine 
thanks again Rm-hull.
